"""add mp users table

Revision ID: 85562de34b0e
Revises: e50eb197224a
Create Date: 2022-12-13 17:18:58.604731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85562de34b0e'
down_revision = 'e50eb197224a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mp_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('mp_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mp_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_mp_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mp_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mp_user_username'))
        batch_op.drop_index(batch_op.f('ix_mp_user_email'))

    op.drop_table('mp_user')
    # ### end Alembic commands ###
