"""add is_host flag

Revision ID: a98d88a66e1d
Revises: 6b0b089a3028
Create Date: 2023-01-11 14:18:03.748230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98d88a66e1d'
down_revision = '6b0b089a3028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_host', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_users', schema=None) as batch_op:
        batch_op.drop_column('is_host')

    # ### end Alembic commands ###
