"""restart db schma

Revision ID: e87047ebcce6
Revises: 
Create Date: 2022-12-27 14:56:36.464633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87047ebcce6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mp_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('verified', sa.Boolean(create_constraint=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('mp_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mp_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_mp_user_username'), ['username'], unique=True)

    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['mp_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    with op.batch_alter_table('mp_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mp_user_username'))
        batch_op.drop_index(batch_op.f('ix_mp_user_email'))

    op.drop_table('mp_user')
    # ### end Alembic commands ###
