"""add verified column

Revision ID: f348b38c2678
Revises: 85562de34b0e
Create Date: 2022-12-24 18:07:37.427294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f348b38c2678'
down_revision = '85562de34b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mp_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(create_constraint=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mp_user', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
